== Rendu

Le projet doit être rendu sous la forme d'un repository (gitlab ou github)

Le projet est à faire maximum en trinôme.

Vous pouvez ajouter un README si vous avez un choix à justifier ou un blocage.

Il doit être rendu au plus tard le 25 janvier à 23h59

== Sujet

Le but de ce projet est de créer 3 services pour faire de la gestion de salle.

Les trois services sont les suivants :

- Peoples : un référentiel de personnes qui peuvent utiliser les salles.
- Reservation : le service de réservation de salles.
- BFF : Back For Front, un service qui fait le lien entre une application front et les deux autres services.
Ici elle fait l'aggrégation des données des deux autres services.

Un 4eme service (rooms) existe déjà pour avoir les informations sur les salles (nom, taille, heures possibles de réservation, ...).
Ce service n'a pas besoin d'être modifié dans le cadre de ce projet. Il sera remplacé par une autre implementation au moment de la notation.

Chaque service a sa propre spécification, des contraintes sont à respecter pour chaque service. +
Elles ne sont pas impératives,
par exemple s'il est demandé une base de donnée h2, il vaut mieux une version HashMap en mémoire qu'un service qui ne fonctionne pas.

La liste des APIs doit inclure au minimum les endpoints demandés, mais il est possible d'en ajouter d'autres si nécessaire.

Des requetes Bruno sont fournies pour tester les services (et garantir le format attendu)

== Peoples

Le service Peoples est un service qui permet de gérer les personnes qui peuvent utiliser les salles.

Contraintes :

* Ce service doit fournir une implémentation de la "base de donnée" :
** en h2 par default,
** avec une hashmap si le profile DEV est activé. 
*** /!\ Par souci de simplification, ce n'est pas grave si une connexion h2 et son repo jpa sont créées, il faut juste que le code utilise la hashmap
* Ce service ne doit pas utiliser les annotations `@Compoment`, `@Service`, `@Repository`, `@Controller`.
** @RestController peut-être utilisé, mais uniquement dans le cadre d'un controlleur HTTP
* Ce service doit avec une architecture en couche/package :
** La couche `controlleur` qui fait la validation des données et la transformation DTO -> Format interne.
** La couche `service` qui fait la logique métier.
** La couche `repository` qui fait la gestion de la base de donnée (ça peut être le repository JPA).

Une personne se présente sous la forme suivante :

[source,json]
----
{
  "firstName": "John",
  "lastName": "Doe",
  "age": 30,
  "address": {
    "street": "123 Main St",
    "city": "Nantes",
    "zipCode": "44000",
    "country": "France"
  }
}
----

